vim.cmd("set clipboard=unnamedplus")
vim.cmd("set hidden")
vim.cmd("set mouse=a")
vim.cmd("set smarttab")
vim.cmd("set autoindent")
vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.g.mapleader = " "
